services:
  flask-app:
    image: lucascx/flask-todo:latest
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      MONGO_IP: "mongo:27017"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - mongo
    networks:
      - flask-mongo-network

  mongo:
    build:
      context: .
      dockerfile: mongo_dockerfile
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ MONGO_INITDB_ROOT_USERNAME }"
      MONGO_INITDB_ROOT_PASSWORD: "${ MONGO_INITDB_ROOT_PASSWORD }"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: --config /etc/mongodb/mongod.conf
    networks:
      - flask-mongo-network

networks:
  flask-mongo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
volumes:
  mongo_data:
    driver: local