- hosts: "{{ server_ip }}"
  become: true
  tasks:
    - name: Update yum repository
      yum:
        name: "*"
        state: latest

    - name: Install openssl
      yum:
        name:
          - "openssl"
        state: present

    - name: Create directory for certificates
      ansible.builtin.file:
        path: /etc/mongodb/certs
        state: directory
        mode: '0755'

    - name: Generate private key
      ansible.builtin.shell: openssl genpkey -algorithm RSA -out mongodb-key.pem -pkeyopt rsa_keygen_bits:2048
      args:
        chdir: /etc/mongodb/certs

    - name: Generate CSR
      ansible.builtin.shell: |
        openssl req -new -key mongodb-key.pem -out mongodb.csr -subj "/C=US/ST=Some-State/L=Some-City/O=MyOrg/OU=IT/CN=myserver.example.com/emailAddress=admin@example.com"
      args:
        chdir: /etc/mongodb/certs

    - name: Generate certificate
      ansible.builtin.shell: |
        openssl x509 -req -in mongodb.csr -signkey mongodb-key.pem -out mongodb-cert.pem -days 365
      args:
        chdir: /etc/mongodb/certs

    - name: Combine key and cert into one file
      ansible.builtin.shell: cat mongodb-cert.pem mongodb-key.pem > mongodb.pem
      args:
        chdir: /etc/mongodb/certs

    - name: Copy certs folder from host to mongo container
      ansible.builtin.shell: docker cp /etc/mongodb/certs mongo:/etc/mongodb/certs

    - name: Add combined PEM file path to mongo config in the container
      ansible.builtin.shell: |
        docker exec -it mongo bash\
        sed -i '/^net:/a\
          ssl:\
            mode: requireSSL\
            PEMKeyFile: /etc/mongodb/certs/mongodb.pem' /etc/mongod.conf

    - name: Restart mongodb container after configuration change
      ansible.builtin.shell: docker restart mongo