- hosts: "{{ server_ip }}"
  become: true
  tasks:
    - name: Update yum repository
      yum:
        name: "*"
        state: latest

    - name: Install openssl
      yum:
        name:
          - "openssl"
        state: present

    - name: Create directory for certificates
      ansible.builtin.file:
        path: /home/ec2-user/certs
        state: directory
        mode: '0755'

    - name: Generate certificate
      ansible.builtin.shell: |
        openssl req -newkey rsa:2048 -new -x509 -days 3650 -nodes -out mongodb-cert.crt -keyout mongodb-cert.key \
        -subj "/C=US/ST=Some-State/L=Some-City/O=MyOrg/OU=IT/CN=myserver.example.com/emailAddress=admin@example.com"
      args:
        chdir: /home/ec2-user/certs

    - name: Combine MongoDB certificate and key
      ansible.builtin.shell: cat mongodb-cert.key mongodb-cert.crt > mongodb.pem
      args:
        chdir: /home/ec2-user/certs

    - name: Change file permissions to 644 for PEM and config files
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0644'
      with_items:
        - /home/ec2-user/certs/mongodb.pem
        - /home/ec2-user/certs/mongodb-cert.key
        - /home/ec2-user/certs/mongodb-cert.crt
