- hosts: "{{ server_ip }}"
  become: true
  tasks:
    - name: Update yum repository
      yum:
        name: "*"
        state: latest

    - name: Install openssl
      yum:
        name:
          - "openssl"
        state: present

    - name: Create directory for certificates
      ansible.builtin.file:
        path: /home/ec2-user/certs
        state: directory
        mode: '0755'

    - name: Generate private key
      ansible.builtin.shell: openssl genpkey -algorithm RSA -out mongodb-key.pem -pkeyopt rsa_keygen_bits:2048
      args:
        chdir: /home/ec2-user/certs

    - name: Generate CSR
      ansible.builtin.shell: |
        openssl req -new -key mongodb-key.pem -out mongodb.csr -subj "/C=US/ST=Some-State/L=Some-City/O=MyOrg/OU=IT/CN=myserver.example.com/emailAddress=admin@example.com"
      args:
        chdir: /home/ec2-user/certs

    - name: Generate certificate
      ansible.builtin.shell: |
        openssl x509 -req -in mongodb.csr -signkey mongodb-key.pem -out mongodb-cert.pem -days 365
      args:
        chdir: /home/ec2-user/certs

    - name: Combine key and cert into one file
      ansible.builtin.shell: cat mongodb-cert.pem mongodb-key.pem > mongodb.pem
      args:
        chdir: /home/ec2-user/certs