- hosts: "{{ server_ip }}"
  become: true
  tasks:
    - name: Update yum repository
      yum:
        name: "*"
        state: latest

    - name: Install docker
      yum:
        name:
          - "docker"
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Upload docker-compose file
      ansible.builtin.copy:
        src: ../compose-prod.yml
        dest: /home/ec2-user/compose-prod.yml
        owner: root
        group: root
        mode: '0644'

    - name: Upload mongo_dockerfile file
      ansible.builtin.copy:
        src: ../mongo_dockerfile
        dest: /home/ec2-user/mongo_dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: Upload mongod.conf file
      ansible.builtin.copy:
        src: ../mongod.conf
        dest: /home/ec2-user/mongod.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Run docker compose up
      ansible.builtin.shell: |
        docker-compose -f /home/ec2-user/compose-prod.yml up -d
      environment:
        MONGO_INITDB_ROOT_USERNAME: "{{ mongo_user }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_pass }}"
      register: docker_compose_output

    - name: Debug docker compose output
      ansible.builtin.debug:
        var: docker_compose_output.stdout